language: python

python:
  - "2.7"
  - pypy
  - "3.2"
  - "3.3"

before_install:
    pip install -r requirements.txt

install:
    - python setup.py install

script: make test

services:
  - mongodb
