language: python

python:
  - "2.6"
  - "2.7"
  - pypy
  - "3.2"
  - "3.3"

install:
    - pip install -r requirements.txt
    - python setup.py install
    - pip install coveralls

script:
    coverage run --source=mongu setup.py test

after_success:
    coveralls

services:
  - mongodb
